name: My new CI/CD

on:
  push:
    branches: [ "master" ]
permissions:
  contents: read
  actions: write
  checks: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -DskipTests=true --file pom.xml

    - name: Test with Maven
      run: mvn -B test --batch-mode --no-transfer-progress --file pom.xml
      
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()    # run this step even if previous step failed
      with:
        name: Maven Tests            # Name of the check run which will be created
        path: target/surefire-reports/*.xml    # Path to test results
        reporter: java-junit
        fail-on-error: true # Format of test results
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: fraction
        path: target/*.jar
